name: Push-to-Lightsail

on: push

jobs:
  deploy:
    name: Push to lightsail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my lightsail instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "arn:aws:lightsail:us-east-2:334414210782:Instance/ba06262a-cc71-4cd6-b906-ea84a729ab8e"
          REMOTE_USER: "bitnami"
          TARGET: "/home/bitnami/SampleExpressApp"

